### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by nastys**
Notes:
1 - Not tested
2 - Changelog not updated. If you need to add "Italian language added":

> Aggiunta lingua italiana.

You may need to change something else in the program, I don't know...

### CODE REVIEW

**Comment by VinsCool** [comment]
Cool! :)

Just waiting for mrMysterio to merge :P

**Comment by MrMysterio** [comment]
You need to add the name of the language to the listbox in LangSel.Designer.cs. The list starts at line 47. You may also want to change English to Italian in Langs.cs. It doesn't matter, but it would be easier to read.

**Comment by nastys** [comment]
Added "Italiano" in LangSel.Designer.cs. What do I need to change in Langs.cs exactly?

**Comment by MrMysterio** [comment]
You don't NEED to change anything in Langs.cs, but if you changed #Region ENGLISH_UWIZARD to #Region ITALIAN_UWIZARD, it would be more clear for anybody reading the file.

**Comment by nastys** [comment]
It think you're reading the wrong line...
screenshot

**Comment by MrMysterio** [comment]
Huh?
This is what I see:
image

**Comment by nastys** [comment]
That's the old commit. To see the latest version of the file, click Changes then Uwizard/Langs.cs.

**Pull request merged**
